### ISSUE TITLE
set_lna_gain uses Request::SetVgaGain by mistake

### ISSUE THREAD

**Issue by nitroxis** [newAM/hackrfone#14]
I believe there's a typo here:

https://github.com/newAM/hackrfone/blob/561d31ea3c16e1ec8af8938996597374634613f7/src/lib.rs#L464

This should probably be `Request::SetLnaGain`, no?

**Comment by newAM** [comment]
Yikes, yup, you are correct.

**Comment by newAM** [comment]
Fixed in v0.2.2.

Sorry for the bug :fearful:

**Comment by nitroxis** [comment]
Thanks for the fix! However, setting LNA/VGA gain somehow still has no effect on my HackRF (it does work in other programs). I'm going to investigate further.

**Comment by nitroxis** [comment]
I think I found the problem and created a PR: https://github.com/newAM/hackrfone/pull/16
